---
- name: Create Tenant Namespace
  hosts: localhost
  become: true

  vars:
    namespace_tenant: NS3
    namespace_transit : NStransit
    ip_transit : "10.10.3.1/30"
    ip_namespace : "10.10.3.2/30"
    veth_pgw: NST_{{namespace_tenant}}_veth0
    veth_t: NST_{{namespace_tenant}}_veth1
    

  tasks:
    - name: Create Namespace
      command: ip netns add {{ namespace_tenant }}

    - name: Create veth pair
      command: ip link add {{ veth_pgw }} type veth peer name {{ veth_t }}

    - name: Move veth_t to Namespace
      command: ip link set {{ veth_t }} netns {{ namespace_tenant }}

    - name: Move veth_pgw to transit Namespace
      command: ip link set {{ veth_pgw }} netns {{ namespace_transit }}


    - name: Bring up veth_pgw in transit Namespace
      command: ip netns exec {{namespace_transit}} ip link set dev {{ veth_pgw }} up

    - name: Bring up veth_t in tenant
      command: ip netns exec {{ namespace_tenant }} ip link set dev {{ veth_t }} up

    - name: setting ip address in transit Namespace
      command: ip netns exec {{namespace_transit}} ip addr add {{ip_transit}} dev {{ veth_pgw }}

    - name: setting ip address in Namespace
      command: ip netns exec {{namespace_tenant}} ip addr add {{ip_namespace}} dev {{ veth_t }}




