- name: Configure iptables rule on FW
  hosts: "{{host}}"
  become: true    
  tasks:
    - name: Add iptables rule for FORWARD chain
      iptables:
        chain: FORWARD
        table: filter
        source: "{{ src_ip }}"
        destination: "{{ dest_ip }}"
        protocol: "{{ protocol }}"
        source_port: "{{ src_port }}"
        destination_port: "{{ dest_port }}"
		    limit: "{{ threshold }}/second"
        jump: "{{action}}"
        state: present