- name: Configure iptables rule on FW
  hosts: "{{host}}"
  become: true
  vars:
    log_prefix: "IPTABLES-DROPPED: "    
  tasks:
    - name: Add iptables rule for FORWARD chain
      iptables:
        chain: FORWARD
        table: filter
        source: "{{ src_ip }}"
        destination: "{{ dest_ip }}"
        protocol: "{{ protocol }}"
        source_port: "{{ src_port }}"
        destination_port: "{{ dest_port }}"
        match: state
        state: NEW,RELATED,ESTABLISHED
        limit: "{{ threshold }}/second"
        jump: "{{ policy_action }}"
        state: present
      when: protocol != "icmp"

    - name: Add iptables rule for ICMP in FORWARD chain
      iptables:
        chain: FORWARD
        table: filter
        source: "{{ src_ip }}"
        destination: "{{ dest_ip }}"
        match: state
        state: NEW,RELATED,ESTABLISHED
        protocol: icmp
        limit: "{{ threshold }}/second"
        jump: ACCEPT
        state: present
      when: protocol == "icmp"


    - name: Add iptables rule to log dropped packets
      iptables:
        chain: FORWARD
        table: filter
        source: "{{ src_ip }}"
        destination: "{{ dest_ip }}"
        protocol: "{{ protocol }}"
        source_port: "{{ src_port }}"
        destination_port: "{{ dest_port }}"
        jump: "LOG"
        log_prefix: "{{ log_prefix }}"
        log_level: warning
        state: present
      when: protocol != "icmp"

    - name: Add iptables rule to log dropped packets
      iptables:
        chain: FORWARD
        table: filter
        source: "{{ src_ip }}"
        destination: "{{ dest_ip }}"
        protocol: icmp
        jump: "LOG"
        log_prefix: "{{ log_prefix }}"
        log_level: warning
        state: present
      when: protocol == "icmp"

    - name: Add iptables rule for drop exceeded FORWARD chain
      iptables:
        chain: FORWARD
        table: filter
        source: "{{ src_ip }}"
        destination: "{{ dest_ip }}"
        protocol: "{{ protocol }}"
        source_port: "{{ src_port }}"
        destination_port: "{{ dest_port }}"
        jump: DROP
        state: present
      when: protocol != "icmp"

    - name: Add iptables rule for drop exceeded ICMP in FORWARD chain
      iptables:
        chain: FORWARD
        table: filter
        source: "{{ src_ip }}"
        destination: "{{ dest_ip }}"
        protocol: icmp
        jump: DROP
        state: present
      when: protocol == "icmp"
