- name: Configure iptables rule on FW
  hosts: localhost
  become: true
  vars:
    Src: "192.168.1.0"
    dst: "8.8.8.8"
    sport: "80"
    dport: "443"
    protocol: "tcp"
	  threshold: "10"
  tasks:
    - name: Add iptables rule for FORWARD chain
      iptables:
        chain: FORWARD
        table: filter
        source: "{{ Src }}/24"
        destination: "{{ dst }}"
        protocol: "{{ protocol }}"
        sport: "{{ sport }}"
        dport: "{{ dport }}"
        limit: "{{ threshold }}/second"
        jump: ACCEPT