- name: Create and configure OVS bridge
  hosts: localhost
  become: yes
  vars:
    namespace_tenant: T1
    vm_name: "Guest-VM5"
    vm_net_name: net1
    vm_net: "{{ namespace_tenant }}_{{vm_net_name}}_BR"
    src_dir: "/home/csc792/FwaaS-VPC"

  tasks:
    - name: push network template
      template:
        src: "{{ src_dir }}/interface-template.xml.j2"
        dest: "{{ src_dir }}/{{ vm_name}}_{{ vm_net}}.xml"
      register: template_result

    - name: attach network to VM
      command: virsh attach-device {{ vm_name}} {{template_result.dest }} --live --config

    - name: Remove xml file
      file:
        path: "{{ template_result.dest }}"
        state: absent
