---
- name: Create Tenant Namespace
  hosts: localhost
  become: true

  vars:
    bridge_pgw: BR_PGW_T
    veth_pgw: PGW_{{namespace_tenant}}_veth0
    veth_t: PGW_{{namespace_tenant}}_veth1
    veth_defroute: 10.3.6.1

  tasks:
    - name: Create Namespace
      command: ip netns add {{ namespace_tenant }}

    - name: Create veth pair
      command: ip link add {{ veth_pgw }} type veth peer name {{ veth_t }}

    - name: Move veth_t to Namespace
      command: ip link set {{ veth_t }} netns {{ namespace_tenant }}

    - name: Move veth_pgw to OVS PGW Bridge
      command: ovs-vsctl add-port {{ bridge_pgw }}  {{ veth_pgw }}


    - name: Bring up veth_pgw
      command: ip link set dev {{ veth_pgw }} up

    - name: Bring up veth_t
      command: ip netns exec {{ namespace_tenant }} ip link set dev {{ veth_t }} up

    - name: assign as DHClient for veth_t
      command: ip netns exec {{ namespace_tenant }} dhclient PGW_{{ namespace_tenant }}_veth1

    - name: Create folder for Namespace
      file:
        path: "/etc/netns/{{ namespace_tenant }}"
        state: directory

    - name: Configure NAT from FW
      command: ip netns exec {{ namespace_tenant }} iptables -t nat -I POSTROUTING 1 -o {{ veth_t }} -j MASQUERADE







