---
- name: Create and configure OVS bridge
  hosts: localhost
  become: yes
  vars:
    namespace_tenant: T1
    vm_net_name: net1
    vm_net: "{{ namespace_tenant }}_{{vm_net_name}}"
    tenant_net_gw_ip: 10.3.3.1/24
    dhcp_start: 10.3.3.2
    dhcp_end: 10.3.3.254
    dhcp_mask: 255.255.255.0
  tasks:
    - name: Create OVS bridge
      openvswitch_bridge:
        bridge: "BR_{{ vm_net }}"
        state: present

    - name: Set OVS interface to UP
      command: "ip link set BR_{{ vm_net }} up"

    - name: Create veth pair
      command: ip link add veth0_{{ vm_net }} type veth peer name veth1_{{ vm_net }}

    - name: Move veth peer to Namespace
      command: ip link set veth1_{{ vm_net }} netns {{ namespace_tenant }}

    - name: Move veth_pgw to OVS PGW Bridge
      command: ovs-vsctl add-port BR_{{ vm_net }}  veth0_{{ vm_net }}

    - name: Bring up veth peer
      command: ip link set dev veth0_{{ vm_net }} up

    - name: Bring up veth_t
      command: ip netns exec {{ namespace_tenant }} ip link set dev veth1_{{ vm_net }} up

    - name: Assign IP address
      command: ip netns exec {{ namespace_tenant }} ip addr add {{ tenant_net_gw_ip }} dev veth1_{{ vm_net }}

    - name: Create the DHCP file in Namespace
      become: true
      file:
        path: "/etc/netns/{{ namespace_tenant }}/{{ vm_net }}.conf"
        state: touch


    - name: Create an empty dhcpd.conf file in Host
      file:
        path: "/etc/{{ vm_net }}.conf"
        state: touch

    - name: Add lines to DHCP file
      lineinfile:
        path: "/etc/netns/{{ namespace_tenant }}/{{ vm_net }}.conf"
        line: "{{ item }}"
      with_items:
        - "strict-order"
        - "user=libvirt-dnsmasq"
        - "except-interface=lo"
        - "bind-dynamic"
        - "interface=veth1_{{ vm_net }}"
        - "dhcp-range={{dhcp_start}},{{dhcp_end}},{{dhcp_mask}}"
        - "dhcp-no-override"
        - "dhcp-authoritative"
        - "dhcp-lease-max=253"



    - name: run the DHCP file with dnsmasq
      command: "ip netns exec {{namespace_tenant}} dnsmasq -C /etc/netns/{{namespace_tenant}}/{{vm_net}}.conf"
