- name: Configure iptables rule on FW
  hosts: "{{host}}"
  become: true    
  vars:
    log_prefix: "IPTABLES-DROPPED: "
  tasks:
    - name: Del iptables rule for FORWARD chain
      iptables:
        chain: FORWARD
        table: filter
        source: "{{ src_ip }}"
        destination: "{{ dest_ip }}"
        protocol: "{{ protocol }}"
        source_port: "{{ src_port }}"
        destination_port: "{{ dest_port }}"
        limit: "{{ threshold }}/second"
        jump: "{{policy_action}}"
        state: absent

    - name: Del iptables rule to log dropped packets
      iptables:
        chain: FORWARD
        table: filter
        source: "{{ src_ip }}"
        destination: "{{ dest_ip }}"
        protocol: "{{ protocol }}"
        source_port: "{{ src_port }}"
        destination_port: "{{ dest_port }}"
        limit: "{{ threshold }}/second"
        jump: "LOG"
        log_prefix: "{{ log_prefix }}"
        log_level: warning
        state: absent
