- name: Configure Initial setup on FW
  hosts: T3FW
  become: true    
  vars:
    IN_int: "enp8s0"
    OUT_int: "enp9s0"
    OUT_gw: "10.8.8.1"
    IN_gw: "10.7.7.1"
  tasks:

    - name: Add iptables rule for NAT public traffic
      command: iptables -t nat -I POSTROUTING 1 -o {{ OUT_int }} -j MASQUERADE
      
    - name: Enable IP forwarding
      sysctl:
        name: net.ipv4.ip_forward
        value: 1
        state: present
        reload: yes

    - name: Add rule to accept all established connection or is related to an established connection
      command: iptables -A INPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT

    - name: Add iptables rule to drop all invalid packets
      command: iptables -A INPUT -m conntrack --ctstate INVALID -j DROP

    - name: Add rule to accept all established connection or is related to an established connection
      command: iptables -I FORWARD -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT

    - name: Add iptables rule to drop all invalid packets
      command: iptables -I FORWARD -m conntrack --ctstate INVALID -j DROP

    - name: Add rule to default deny  
      command: iptables -P FORWARD DROP

    - name: Add route for the internal 10.0.0.0/8 network
      command: ip route add 10.0.0.0/8 via {{ IN_gw }} dev {{ IN_int }}

    - name: Add route for the internal 172.16.0.0/12 network
      command: ip route add 172.16.0.0/12 via {{ IN_gw }} dev {{ IN_int }}

    - name: Add route for the internal 192.168.0.0/16 network
      command: ip route add 192.168.0.0/16 via {{ IN_gw }} dev {{ IN_int }}
      
    - name: Add default route towards external interface
      command: ip route add default via {{ OUT_gw }} dev {{ OUT_int }}
